#ifndef _STATUS_ID_H_
#define _STATUS_ID_H_

#define WALK_LEFT_ID "WLS"
#define WALK_RIGHT_ID "WRS"
#define STAND_LEFT_ID "SLS"
#define STAND_RIGHT_ID "SRS"
#define JUMP_LEFT_ID "JMPLS"
#define JUMP_RIGHT_ID "JMPRS"
#define FALL_LEFT_ID "FLLLS"
#define FALL_RIGHT_ID "FLLRS"
#define WALK_ATTACK_LEFT_ID "WATTLS"
#define WALK_ATTACK_RIGHT_ID "WATTRS"
#define STAND_ATTACK_LEFT_ID "SWATTLS"
#define STAND_ATTACK_RIGHT_ID "SWATTRS"

#endif // _STATUS_ID_H
